spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: mini-5
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa
    password:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: sa
      password:
  h2:
    console:
      enabled: true
  jpa:
    #    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate.format_sql: true  # debug query more pretty
#      hibernate.default_batch_fetch_size: 50 # select complicated query bulk (one of solution n+1)

api:
  riot:
    key: ${RIOT_API_KEY}

server:
  servlet:
    encoding:
      force-response: true